pipeline:
  node:
      image: node
      commands:
        - node -v
  
  docker:
    image: plugins/docker
    registry: eve-registry:5000/test/tost
    insecure: true
    mirror: https://registry.docker-cn.com
