pipeline:
  node:
      image: node
      commands:
        - node -v
  python:
      image: python
      commands:
        - python --version
  haskell:
    image: haskell
    commands:
      - haskell --version
