pipeline:
  node:
      image: node
      commands:
        - node -v
        - npm -v
  
  docker:
    image: plugins/docker
    repo: eve-registry:5000/eve
    registry: eve-registry:5000
    insecure: true
    mirror: https://registry.docker-cn.com
