pipeline:
  node:
      image: node
      commands:
        - node -v
  
  docker:
    image: plugins/docker
    repo: eve-registry/test
    registry: eve-registry
    mirror: https://registry.docker-cn.com
