pipeline:
  node:
      image: node
      commands:
        - node -v
  
  docker:
    image: plugins/docker
    repo: eve-registry:5000/eve-registry/test
    registry: eve-registry:5000
    mirror: https://registry.docker-cn.com
