pipeline:
  node:
      image: node
      commands:
        - node -v
  python:
      image: python
      commands:
        - python --version
  php:
    image: php
    commands:
      - php --version
