workspace:
  base: /go
  path: src/github.com/amiralibamilo/drone-golang-example

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  node:
      image: node
      commands:
        - node -v
  python:
      image: python
      commands:
        - python --version
  php:
    image: php
    commands:
      - php --version
