pipeline:
  node:
      image: node
      commands:
        - node -v
        - npm -v
  
  docker:
    image: plugins/docker
    repo: localhost:5000/eve-registry/test
    registry: localhost:5000
    mirror: https://registry.docker-cn.com
