pipeline:
  node:
      image: node
      commands:
        - node -v
  
  docker:
    image: plugins/docker
    repo: eve-registry/test
    tags: latest
    mirror: registry.docker-cn.com/library/ubuntu
